# This is a basic workflow to help you get started with Actions

name: checkov-action

# Run on each push
on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: A job to scan infra code for security mistakes
    steps:
    - name: Run Checkov action
      id: checkov
      uses: cmavr8/checkov-action@master