# This is a basic workflow to help you get started with Actions

name: checkov-action

# Run on each push
on: [push]

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Checkov action
        id: checkov
        uses: cmavr8/checkov-action@v5
